/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CompareView: typeof import('./src/components/CompareView.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElRadioButton: typeof import('element-plus/es')['ElRadioButton']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElSlider: typeof import('element-plus/es')['ElSlider']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    HistoryList: typeof import('./src/components/HistoryList.vue')['default']
    RasterParamPanel: typeof import('./src/components/RasterParamPanel.vue')['default']
    ResultBar: typeof import('./src/components/ResultBar.vue')['default']
    TraceParamPanel: typeof import('./src/components/TraceParamPanel.vue')['default']
    UploadPanel: typeof import('./src/components/UploadPanel.vue')['default']
  }
}
