/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CompareView: typeof import('./src/components/CompareView.vue')['default']
    CompressParamPanel: typeof import('./src/components/CompressParamPanel.vue')['default']
    CropEditor: typeof import('./src/components/CropEditor.vue')['default']
    CropParamPanel: typeof import('./src/components/CropParamPanel.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElRadioButton: typeof import('element-plus/es')['ElRadioButton']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElSlider: typeof import('element-plus/es')['ElSlider']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    ExportParamPanel: typeof import('./src/components/ExportParamPanel.vue')['default']
    HistoryList: typeof import('./src/components/HistoryList.vue')['default']
    QueueResultList: typeof import('./src/components/QueueResultList.vue')['default']
    RasterParamPanel: typeof import('./src/components/RasterParamPanel.vue')['default']
    ResizeParamPanel: typeof import('./src/components/ResizeParamPanel.vue')['default']
    ResultBar: typeof import('./src/components/ResultBar.vue')['default']
    TraceParamPanel: typeof import('./src/components/TraceParamPanel.vue')['default']
    TransformParamPanel: typeof import('./src/components/TransformParamPanel.vue')['default']
    UploadPanel: typeof import('./src/components/UploadPanel.vue')['default']
  }
}
